//
//  PubadsWrapperModel.swift
//  VastClientTests
//
//  Created by Jan Bednar on 20/11/2018.
//  Copyright © 2018 John Gainfort Jr. All rights reserved.
//

import Foundation
@testable import VastClient

extension VastModel {
    static let pubadsWrapperModel: VastModel = {
        let adSystem: VastAdSystem? = VastAdSystem(version: nil, system: "GDFP")
        let impressions = VastImpression(id: nil, url: URL(string: "https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjsusehFIU3B_zjjHnP1rbTsQcL1DuMegayPENgGMzl2F4q4VSRE_hEPYiSdSxk7aFdsrRhDOKl1bsIESKtV0lYZYEZnBkG1DF0tX3bIcWIBEuZzdRcm_O4hDvDyg6chnV5l6EyOFjgWAmPIgfZdYlE6CpcsH1vLyuqHR-ouBR81NAAncv4BBMRsCOmfWJTTbyVYYhbsCJSoXZxrctI356Px2qlI-mf-hBJh5mkbb4GH4UP0YifKTeaKuphv_s0AyuE24Vurs&sig=Cg0ArKJSzDInvRkrwjqbEAE&adurl=")!)
        let pricing: VastPricing? = nil
        let errors = [URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=videoplayfailed[ERRORCODE]")!]
        let categories: [VastAdCategory] = []
        let videoClicks: [VastVideoClick] = [
            VastVideoClick(id: "GDFP", type: .clickTracking, url: URL(string: "https://pubads.g.doubleclick.net/pcs/click?xai=AKAOjstMlDCafE7oEhtiscJjbFb_QU2dbtjzxonRFAGIccKWH0B_elIfZxpBap-BOoAHo8wNWDIlr5glVzwXHasZG6PFPEijIrUqIPu2z37zRAZKoCOGowJPqj0mjm87hi1nbRhkVE3fA4R7GYN1f0t-98AThUgd5I9Syw6mv-4u6rntuq0uls-MaskPXwS4nv2SX7FoqDm76_6uOBfJPilC6PhXc_AWK_yN_dpiQtnzx95vuEW7aDUAUBVSkKRA6BS2yIaU&sig=Cg0ArKJSzEHEo1EHY3dvEAE&urlfix=1"))
        ]
        let trackingEvents: [VastTrackingEvent] = [
            VastTrackingEvent(type: .start, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=part2viewed&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .firstQuartile, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=videoplaytime25&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .midpoint, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=videoplaytime50&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .thirdQuartile, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=videoplaytime75&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .complete, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=videoplaytime100&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .mute, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=admute&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .unmute, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=adunmute&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .rewind, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=adrewind&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .pause, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=adpause&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .resume, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=adresume&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .fullscreen, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=adfullscreen&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .creativeView, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=vast_creativeview&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .exitFullscreen, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=vast_exit_fullscreen&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .acceptInvitationLinear, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=acceptinvitation&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false),
            VastTrackingEvent(type: .closeLinear, offset: nil, url: URL(string: "https://pubads.g.doubleclick.net/pagead/conversion/?ai=BFrjb7vnzW9TdMMOckwOBp4mgBdzhwK5FAAAAEAEg3rDkITgAWM3ywIKDBGDJjsaN9KTQGbIBD3d3dy5ucG9zdGFydC5ubLoBCzMyMHgyNDBfeG1syAEF2gH_AWh0dHBzOi8vd3d3Lm5wb3N0YXJ0Lm5sL3BhdXcvMTUtMTAtMjAxOC9CVl8xMDEzODg2MTg_dHR5cGU9Y2hvaWNlJnRldmVudD0lN0IlMjJzcHZpZCUyMiUzQSUyMjAlM0FaTklYcHlGekRuTEFXT09TclZhd0R2SWlCN3kzTFdBdSUyMiUyQyUyMmNvbVNjb3JlTmFtZSUyMiUzQSUyMm5wby5ob21lLmluZGV4JTIyJTJDJTIyYnJhbmQlMjIlM0ElMjJucG9wb3J0YWwlMjIlMkMlMjJzZWN0aW9uJTIyJTNBJTIyaG9tZSUyMiUyQyUyMmJyb2FkY2FzdGVyJZgCqMMBqQJ9vD4uujuzPsACAuACAOoCFy85MjMzL25wb3BsYXllci5ubC9wYXV3-AKB0h6QA_ABmAOMBqgDAeAEAdIFBhC6v7-HEpAGAaAGJNgHAOAHH9IIBwiAYRABGAE&sigh=IQl-Kbw5tz4&label=adclose&ad_mt=[AD_MT]&acvw=[VIEWABILITY]&gv=[GOOGLE_VIEWABILITY]"), tracked: false)
        ]
        let mediaFilesArray: [VastMediaFile] = []
        let interactiveMediaFiles: [VastInteractiveCreativeFile] = []
        let mediaFiles = VastMediaFiles(mediaFiles: mediaFilesArray, interactiveCreativeFiles: interactiveMediaFiles)
        let icons: [VastIcon] = []
        
        let linear: VastLinearCreative? = VastLinearCreative(skipOffset: nil, duration: nil, adParameters: nil, videoClicks:videoClicks, trackingEvents: trackingEvents, files: mediaFiles, icons: icons)
        let universalAdId: VastUniversalAdId? = nil
        
        let creative = VastCreative(id: "138249517389", adId: nil, sequence: 1, apiFramework: nil, universalAdId: universalAdId, creativeExtensions: [], linear: linear, nonLinearAds: nil, companionAds: nil)
        
        let extensions: [VastExtension] = [
            VastExtension(type: "geo", creativeParameters: []),
            VastExtension(type: "pod", creativeParameters: []),
            VastExtension(type: "activeview", creativeParameters: []),
            VastExtension(type: "metrics", creativeParameters: []),
            VastExtension(type: "ShowAdTracking", creativeParameters: []),
            VastExtension(type: "wrapper_info", creativeParameters: []),
            VastExtension(type: "video_ad_loaded", creativeParameters: []),
        ]
        
        let adTagUri = URL(string: "test://Pubads_Inline_Model-test")
        let wrapper = VastWrapper(followAdditionalWrappers: nil, allowMultipleAds: nil, fallbackOnNoAd: nil, adTagUri: adTagUri)
        
        let ad = VastAd(type: .wrapper, id: "4847558586", sequence: 1, conditionalAd: nil, adSystem: adSystem, impressions: [impressions], adVerifications: [], viewableImpression: nil, pricing: pricing, errors: errors, creatives: [creative], extensions: extensions, adTitle: nil, adCategories: categories, description: nil, advertiser: nil, surveys: [], wrapper: wrapper)
        
        return VastModel(version: "4.0", ads: [ad], errors: [])
    }()
}
